plugins {
    id 'dev.hybridlabs.fabric'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation("dev.hybridlabs.hapi:hapi-common-1.20.1:1.0.0")
    modImplementation("dev.hybridlabs.hapi:hapi-fabric-1.20.1:1.0.0")

    modImplementation "software.bernie.geckolib:geckolib-fabric-$geckolib_version"

    modApi("com.terraformersmc:modmenu:${modmenu_version}")
}

fabricApi {
    configureDataGeneration {
        setModId("$mod_id")
        outputDirectory = file("src/generated/resources")
        client = true
    }
}

publishMods.platforms.configureEach {
    requires 'fabric-api', 'fabric-language-kotlin', 'geckolib', 'hybrid-api'
}
