plugins {
    id 'dev.hybridlabs.fabric'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation("dev.hybridlabs.hapi:hapi-common-1.21.1:1.0.0")
    modImplementation("dev.hybridlabs.hapi:hapi-fabric-1.21.1:1.0.0")

    modApi "software.bernie.geckolib:geckolib-fabric-$geckolib_version"

    modApi("com.terraformersmc:modmenu:${modmenu_version}")
    modImplementation "maven.modrinth:carpet:$carpet_version"
    modRuntimeOnly "io.github.flemmli97:debugutils:$minecraft_version-$debug_utils_version-fabric"
}

fabricApi {
    configureDataGeneration {
        outputDirectory = file("src/generated/resources")
        client = true
    }
}

publishMods.platforms.configureEach {
    requires 'fabric-api', 'fabric-language-kotlin', 'geckolib', 'hybrid-api'
}
