plugins {
    id 'dev.hybridlabs.neoforge'
    id 'org.jetbrains.kotlin.jvm'
}

dependencies {
    implementation "software.bernie.geckolib:geckolib-neoforge-$geckolib_version"

    implementation("dev.hybridlabs.hapi:hapi-neoforge-1.21.1:1.0.0")
}

publishMods.platforms.configureEach {
    requires 'kotlin-for-forge', 'geckolib', 'hybrid-api'
}
